# Generated by Django 5.0.4 on 2024-04-24 05:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=200)),
                ('blog_content', ckeditor.fields.RichTextField()),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
